#!/bin/sh /etc/rc.common
# FHEM Init Script
# remember to change execution permissions of this file
START=99
STOP=15
start() {
	/opt/fhem/fhem.pl /opt/fhem/fhem.cfg
}
stop(){
	/opt/fhem/fhem.pl 7072 shutdown
}
